/**
 * CMP2 Generated Driver File.
 * 
 * @file cmp2.c
 * 
 * @ingroup cmp2
 * 
 * @brief This file contains the API implementation for the CMP2 driver.
 *
 * @version CMP2 Driver Version 2.13.1
*/
 /*
© [2025] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

#include <xc.h>
#include "../cmp2.h"

static void (*CMP2_InterruptHandler)(void);
static void CMP2_DefaultInterruptCallback(void);


void CMP2_Initialize(void) 
{
    /* Disable CMP2 interrupt before configuring the CMP2
      control register. Although a comparator is disabled, an interrupt can be
      generated by changing the output polarity with the CxPOL bit of the
      CMxCON0 register,or by switching the comparator on or off with the CxON
      bit of the CMxCON0 register.*/
    PIE2bits.C2IE = 0;

    // CHYS disabled; CON enabled; CPOL not inverted; CSYNC asynchronous; 
    CM2CON0 = 0x80;

    // CINTN no_intFlag; CINTP intFlag_pos; 
    CM2CON1 = 0x2;
    
    // CNCH Vss; 
    CM2NSEL = 0x7;
    
    // CPCH CIN1+; 
    CM2PSEL = 0x1;    

    CMP2_InterruptCallbackRegister(CMP2_DefaultInterruptCallback);

    // Clearing IF flag before enabling the interrupt.
    PIR2bits.C2IF = 0;     

    // Enabling CMP2 interrupt.
    PIE2bits.C2IE = 1;
}

void CMP2_Enable(void) 
{
    CM2CON0bits.C2ON = 1;
}

void CMP2_Disable(void) 
{
    CM2CON0bits.C2ON = 0;
}

bool CMP2_GetOutputStatus(void) 
{
    return CMOUTbits.MC2OUT;
}

void CMP2_ISR(void) 
{
    // Clear the CMP2 interrupt flag
    PIR2bits.C2IF = 0;

    if(CMP2_InterruptHandler != NULL)
    {
      CMP2_InterruptHandler();
    }
}

void CMP2_InterruptCallbackRegister(void(*callbackHandler)(void))
{
    if(NULL != callbackHandler)
    {
      CMP2_InterruptHandler = callbackHandler;
    }
}

static void CMP2_DefaultInterruptCallback(void)
{
    //Add your interrupt code here or
    //Use CMP2_InterruptCallbackRegister function to use Custom ISR

}